"""Constants for the Multi-Split Zone Controller integration."""

from __future__ import annotations

DOMAIN = "multisplit_zone_controller"

DEFAULT_UPDATE_INTERVAL_SECONDS = 30

CONF_GROUPS = "groups"
CONF_GROUP_ID = "group_id"
CONF_NAME = "name"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_INCOMPATIBLE_MODE_PAIRS = "incompatible_mode_pairs"
CONF_MIN_CHANGEOVER_DWELL_MINUTES = "min_changeover_dwell_minutes"
CONF_ZONES = "zones"
CONF_ZONE_ID = "zone_id"
CONF_HEAD_CLIMATE = "head_climate"
CONF_FUSION = "fusion"
CONF_STRATEGY = "strategy"
CONF_HEAD_TEMP_SENSOR = "head_temp_sensor"
CONF_HEAD_HUMIDITY_SENSOR = "head_humidity_sensor"
CONF_EXTERNAL_TEMP_SENSORS = "external_temp_sensors"
CONF_EXTERNAL_HUMIDITY_SENSORS = "external_humidity_sensors"
CONF_HEAD_WEIGHT = "head_weight"
CONF_STALE_AFTER_SECONDS = "stale_after_seconds"
CONF_ENTITY_ID = "entity_id"
CONF_WEIGHT = "weight"
CONF_CALIBRATION_OFFSET = "calibration_offset"
CONF_SAFETY = "safety"
CONF_MIN_TEMP = "min_temp"
CONF_MAX_TEMP = "max_temp"
CONF_TARGET_TEMP_STEP = "target_temp_step"
CONF_DEFAULT_TARGET = "default_target_temperature"
CONF_DEMAND_DEADBAND = "demand_deadband"

CONF_OCCUPANCY = "occupancy"
CONF_OCCUPANCY_SOURCES = "sources"
CONF_OCCUPANCY_KIND = "kind"
CONF_OCCUPANCY_LINGER_MINUTES = "linger_minutes"
CONF_OCCUPANCY_CONFIRMED_THRESHOLD = "confirmed_threshold"
CONF_OCCUPANCY_EXPECTED_THRESHOLD = "expected_threshold"
CONF_SETBACK = "setback"
CONF_SETBACK_OFFSET_HEAT = "offset_heat"
CONF_SETBACK_OFFSET_COOL = "offset_cool"
CONF_SETBACK_UNOCC_WEIGHT = "unoccupied_comfort_weight"

CONF_PRECONDITIONING = "pre_conditioning"
CONF_PRECOND_ENABLED = "enabled"
CONF_PRECOND_DEFAULT_HEATING_RATE = "default_heating_rate"
CONF_PRECOND_DEFAULT_COOLING_RATE = "default_cooling_rate"
CONF_PRECOND_MAX_LEAD_MINUTES = "max_lead_minutes"
CONF_PRECOND_EXPECTED_TIMEOUT_MINUTES = "expected_timeout_minutes"
CONF_PRECOND_RATE_ALPHA = "rate_alpha"

CONF_FAN = "fan"
CONF_FAN_ENTITY_ID = "fan_entity_id"
CONF_FAN_ENABLED = "enabled"
CONF_FAN_DIRECTION_HEAT = "direction_in_heat"
CONF_FAN_DIRECTION_COOL = "direction_in_cool"
CONF_FAN_LOCKOUT_ENTITY = "lockout_entity_id"
CONF_FAN_MAX_SPEED_OCC = "max_speed_pct_occupied"
CONF_FAN_MAX_SPEED_UNOCC = "max_speed_pct_unoccupied"
CONF_FAN_MAX_CREDIT = "max_apparent_temp_credit"
CONF_FAN_DEVIATION_PER_STEP = "deviation_per_step"

CONF_OCCUPANCY_SOURCE = "occupancy_source"
CONF_OCCUPANCY_BOOST = "occupancy_boost"

CONF_AUX_HEAT = "aux_heat"
CONF_AUX_ENABLED = "enabled"
CONF_AUX_DEVICE_ENTITY_ID = "device_entity_id"
CONF_AUX_DEVICE_TYPE = "device_type"
CONF_AUX_TARGET_TEMPERATURE = "aux_target_temperature"
CONF_AUX_SAFETY_FLOOR_MARGIN = "safety_floor_margin"
CONF_AUX_DEACTIVATION_MARGIN = "deactivation_margin"
CONF_AUX_OUTDOOR_LOCKOUT_TEMP = "outdoor_lockout_temp"
CONF_AUX_OUTDOOR_TEMP_SENSOR = "outdoor_temp_sensor"
CONF_AUX_FAULT_ON_HEAD_UNAVAILABLE = "fault_on_head_unavailable"
CONF_AUX_SETTLE_SECONDS = "settle_seconds"

CONF_HUMIDITY = "humidity"
CONF_HUMIDITY_TARGET = "target_humidity"
CONF_HUMIDITY_TOLERANCE_BAND = "tolerance_band"
CONF_HUMIDITY_WEIGHT = "weight"
CONF_HUMIDITY_DEHUMIDIFY_THRESHOLD = "dehumidify_threshold"
CONF_HUMIDITY_DEHUMIDIFY_BONUS = "dehumidify_bonus"

CONF_USE_PSYCHROMETRIC_SCORING = "use_psychrometric_scoring"

CONF_ALWAYS_ASSERT_HEAD_STATE = "always_assert_head_state"

CONF_DISPLAY_THERMOSTATS = "display_thermostats"
CONF_DISPLAY_SYNC_SETPOINT = "sync_setpoint"
CONF_DISPLAY_SYNC_MODE = "sync_mode"
CONF_DISPLAY_SYNC_FAN_MODE = "sync_fan_mode"
CONF_DISPLAY_ALWAYS_ASSERT = "always_assert"
CONF_DISPLAY_CONTRIBUTE_TEMPERATURE = "contribute_temperature"
CONF_DISPLAY_CONTRIBUTE_HUMIDITY = "contribute_humidity"
CONF_DISPLAY_TEMPERATURE_WEIGHT = "temperature_weight"
CONF_DISPLAY_HUMIDITY_WEIGHT = "humidity_weight"
CONF_DISPLAY_AUTO_FAN_MODE = "auto_fan_mode"
CONF_DISPLAY_FAN_ONLY_FAN_MODE = "fan_only_fan_mode"
CONF_DISPLAY_CIRCULATE_FAN_MODE = "circulate_fan_mode"

CONF_DISABLE_DEFAULT_INCOMPATIBLE_MODE_PAIRS = (
    "disable_default_incompatible_mode_pairs"
)

ATTR_BLOCK_REASON = "block_reason"
ATTR_EFFECTIVE_TEMPERATURE = "effective_temperature"
ATTR_EFFECTIVE_HUMIDITY = "effective_humidity"
ATTR_TEMPERATURE_SOURCE = "temperature_source"
ATTR_HUMIDITY_SOURCE = "humidity_source"
ATTR_SAFETY_OVERRIDE = "safety_override"
ATTR_DISPATCHED_MODE = "dispatched_mode"
ATTR_STATUS_MESSAGE = "status_message"

STATUS_IDLE = "idle"
STATUS_RUNNING = "running"
STATUS_BLOCKED = "blocked"
STATUS_SAFETY_FLOOR = "safety_floor_active"
STATUS_SAFETY_CEILING = "safety_ceiling_active"

DIAG_SENSOR_PREFIX = "msz"
